name: PullRequest

on:
  workflow_dispatch: # allow for manual workflow triggering as needed
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  PR-loop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com

      - name: Initialize npm
        run: |
          npm i -g npm
          npm ci

      - name: run CI
        run: |
          npm run ci
